### ISSUE TITLE
Existing dotenv module

### ISSUE THREAD

**Issue by litenite42** [treffner/vdotenv#1]
Hey, 

I just wanted to let you know (in case you hadn't seen it), there's an existing dotenv module for v. You're obviously 1000% free to make a new one; just wanted to point it out in case you had something you wanted to use right away. I just started contributing myself, but there's always more to do if it's more up your alley.

https://github.com/zztkm/vdotenv

**Comment by 7underlines** [comment]
Hi,
yeah I see. Well, I was unable to find it when I started working on this for one of my own apps like one year ago. I thought it might be useful for others as well so I uploaded it here. I only saw the other dotenv module when I submitted my module to vpm and decided to submit it anyway.
So I guess you have choice now. The other module is also incompatible with docker .env because they allow inline comments.
